### ISSUE TITLE
[Check-in] Create initial screens

### ISSUE THREAD

**Issue by mattstibbs** [unconference/unconference-tool#13]
Create some screens to provide the following workflow:

**Comment by mattstibbs** [comment]
![1](https://user-images.githubusercontent.com/774387/41995244-ef7cc6fc-7a48-11e8-810c-0b6a8f1e645b.png)

![2](https://user-images.githubusercontent.com/774387/41995252-f2f6a5be-7a48-11e8-93c4-a8d0994cc45a.png)

![3](https://user-images.githubusercontent.com/774387/41995256-f55dcaa8-7a48-11e8-9cbc-860c109fa876.png)

![4](https://user-images.githubusercontent.com/774387/41995259-fa0725d6-7a48-11e8-9d9b-346b30177380.png)

**Comment by blu3id** [comment]
Possibly https://selectize.github.io/selectize.js/ for type-ahead
