### ISSUE TITLE
Fix security vulnerability 

### ISSUE THREAD

**Issue by cholten99** [unconference/unconference-tool#5]
See prompt from github - one of the NodeJS modules requires updating to new version.

**Comment by mattstibbs** [comment]
Had a brief look at this - looks like the vulnerable package is a dependency of another package - boom.

Hopefully we can just update that but I can’t for the life of me work out how to uplift npm package versions....grrrrr

**Comment by blu3id** [comment]
Dependencies significantly pruned in e6e08cb46e6cbee3455d647fa3ee6b53937cdf97 so no-longer an issue as NodeJS is gone... for-now?
